apiVersion: issues.dana.io/v1alpha1
kind: GithubIssue
metadata:
  name: sample-issue
  namespace: default
spec:
  repo: "https://github.com/matanamar10/python-library-project"
  title: "Sample Issue Title"
  description: "This is a sample description for the GitHub issue created via Kubernetes."